# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:3.20

# set version label
ARG BUILD_DATE
LABEL build_version="Linuxserver.io Build-date:- ${BUILD_DATE}"
LABEL maintainer="Roxedus"

# environment settings
ENV XDG_CONFIG_HOME="/config/xdg"

RUN \
  echo "**** install packages ****" && \
  apk add -U --upgrade --no-cache \
    icu-libs \
    sqlite-libs \
    xmlstarlet

# copy local files
COPY root/ /

# ports and volumes
VOLUME /config
