#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost %s" \
    cd "/app/%s/bin" s6-setuidgid abc "/app/%s/bin/%s" \
    -nobrowser -data=/config
