#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd "/app/%s/bin" s6-setuidgid abc "/app/%s/bin/%s" \
            -nobrowser -data=/config
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd "/app/%s/bin" /app/%s/bin/%s \
            -nobrowser -data=/config
fi
